language: csharp
mono: latest
sudo: false

before_install:
  - export EnableNuGetPackageRestore=true

script: "mono --runtime=v4.0 .nuget/NuGet.exe restore Gherkin.CSharp.sln;xbuild /p:Configuration=Debug;NuGet.exe pack dotnet\Gherkin.NuGetPackages\Gherkin.nuspec"

branches:
  only:
    - master

notifications:
  email:
    - cukes-devs@googlegroups.com
  irc:
    - "irc.freenode.org#cucumber"
