language: objective-c
os: osx
osx_image: xcode7
script: 
 - xcodebuild -version
 - xcodebuild -scheme "GherkinOSX" -configuration Debug CONFIGURATION_BUILD_DIR=build/
 - xcodebuild -scheme "AstGenerator" CONFIGURATION_BUILD_DIR=build/
 - xcodebuild -scheme "TokensGenerator" CONFIGURATION_BUILD_DIR=build/
 # - xcodebuild test -scheme "GherkinTestsOSX"
